{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "\n",
    "class Node:\n",
    "    # 该类为所有其他图节点类的父类\n",
    "    def __init__(self, inputs=[]):\n",
    "        #定义每个节点的输入和输出\n",
    "        self.inputs = inputs\n",
    "        self.outputs = []\n",
    "        \n",
    "        # 每个节点都是其输入节点的输出节点\n",
    "        for n in self.inputs:\n",
    "            n.outputs.append(self)\n",
    "            # set 'self' node as inbound_nodes's outbound_nodes\n",
    "\n",
    "        self.value = None\n",
    "        \n",
    "        self.gradients = {}\n",
    "        # keys are the inputs to this node, and their\n",
    "        # values are the partials of this node with \n",
    "        # respect to that input.\n",
    "        # \\partial{node}{input_i}\n",
    "        \n",
    "\n",
    "    def forward(self):\n",
    "        # 前向传播函数 继承该类的其他类会覆写该函数\n",
    "        '''\n",
    "        Forward propagation. \n",
    "        Compute the output value vased on 'inbound_nodes' and store the \n",
    "        result in self.value\n",
    "        '''\n",
    "\n",
    "        raise NotImplemented\n",
    "    \n",
    "\n",
    "    def backward(self):\n",
    "        # 反向传播函数，继承该类的其他类会覆写该函数\n",
    "\n",
    "        raise NotImplemented\n",
    "        \n",
    "class Input(Node):\n",
    "    # 输入节点，包括神经网络输入节点，权重节点，和偏差节点\n",
    "    def __init__(self):\n",
    "        '''\n",
    "        An Input node has no inbound nodes.\n",
    "        So no need to pass anything to the Node instantiator.\n",
    "        '''\n",
    "        Node.__init__(self)\n",
    "\n",
    "    def forward(self, value=None):\n",
    "        '''\n",
    "        Only input node is the node where the value may be passed\n",
    "        as an argument to forward().\n",
    "        All other node implementations should get the value of the \n",
    "        previous node from self.inbound_nodes\n",
    "        \n",
    "        Example: \n",
    "        val0: self.inbound_nodes[0].value\n",
    "        '''\n",
    "        #定义节点数值\n",
    "        if value is not None:\n",
    "            self.value = value\n",
    "            ## It's is input node, when need to forward, this node initiate self's value.\n",
    "\n",
    "        # Input subclass just holds a value, such as a data feature or a model parameter(weight/bias)\n",
    "        \n",
    "    def backward(self):\n",
    "        #计算节点梯度\n",
    "        self.gradients = {self:0} # initialization \n",
    "        for n in self.outputs: \n",
    "            #以下计算该节点的输出节点对该节点的梯度\n",
    "            grad_cost = n.gradients[self]\n",
    "            self.gradients[self] = grad_cost * 1\n",
    "            \n",
    "        \n",
    "        # input N --> N1, N2\n",
    "        # \\partial L / \\partial N \n",
    "        # ==> \\partial L / \\partial N1 * \\ partial N1 / \\partial N\n",
    " \n",
    "\n",
    "class Add(Node):\n",
    "    def __init__(self, *nodes):\n",
    "        Node.__init__(self, nodes)\n",
    "\n",
    "\n",
    "    def forward(self):\n",
    "        self.value = sum(map(lambda n: n.value, self.inputs))\n",
    "        ## when execute forward, this node caculate value as defined.\n",
    "\n",
    "class Linear(Node):\n",
    "    #全连接网络层的计算\n",
    "    def __init__(self, nodes, weights, bias):\n",
    "        Node.__init__(self, [nodes, weights, bias])\n",
    "\n",
    "    def forward(self):\n",
    "        # 前向传播计算 y = w*x + b\n",
    "        inputs = self.inputs[0].value\n",
    "        weights = self.inputs[1].value\n",
    "        bias = self.inputs[2].value\n",
    "\n",
    "        self.value = np.dot(inputs, weights) + bias\n",
    "        \n",
    "    def backward(self):\n",
    "        # 反向传播计算\n",
    "        # initial a partial for each of the inbound_nodes.\n",
    "        self.gradients = {n: np.zeros_like(n.value) for n in self.inputs}\n",
    "\n",
    "        for n in self.outputs:\n",
    "            # Get the partial of the cost w.r.t this node.\n",
    "            grad_cost = n.gradients[self]\n",
    "            #以下分别计算对inputs， weights, bias的梯度\n",
    "            self.gradients[self.inputs[0]] = np.dot(grad_cost, self.inputs[1].value.T)\n",
    "            self.gradients[self.inputs[1]] = np.dot(self.inputs[0].value.T, grad_cost)\n",
    "            self.gradients[self.inputs[2]] = np.sum(grad_cost, axis=0, keepdims=False)\n",
    "\n",
    "        # WX + B / W ==> X\n",
    "        # WX + B / X ==> W\n",
    "\n",
    "class Sigmoid(Node):\n",
    "    #定义sigmoid函数\n",
    "    def __init__(self, node):\n",
    "        Node.__init__(self, [node])\n",
    "\n",
    "\n",
    "    def _sigmoid(self, x):\n",
    "        return 1./(1 + np.exp(-1 * x))\n",
    "\n",
    "    def forward(self):\n",
    "        #前向 即为sigmoid函数计算\n",
    "        self.x = self.inputs[0].value   # [0] input is a list\n",
    "        self.value = self._sigmoid(self.x)\n",
    "\n",
    "    def backward(self):\n",
    "        #反向传播计算梯度\n",
    "        self.partial = self._sigmoid(self.x) * (1 - self._sigmoid(self.x))\n",
    "        \n",
    "        # y = 1 / (1 + e^-x)\n",
    "        # y' = 1 / (1 + e^-x) (1 - 1 / (1 + e^-x))\n",
    "        \n",
    "        self.gradients = {n: np.zeros_like(n.value) for n in self.inputs}\n",
    "\n",
    "        for n in self.outputs:\n",
    "            grad_cost = n.gradients[self]  # Get the partial of the cost with respect to this node.\n",
    "\n",
    "            self.gradients[self.inputs[0]] = grad_cost * self.partial\n",
    "            # use * to keep all the dimension same!.\n",
    "\n",
    "\n",
    "\n",
    "class MSE(Node):\n",
    "    # 定义平均平方误差\n",
    "    def __init__(self, y, a):\n",
    "        Node.__init__(self, [y, a])\n",
    "\n",
    "\n",
    "    def forward(self):\n",
    "        #前向传播计算\n",
    "        y = self.inputs[0].value.reshape(-1, 1)\n",
    "        a = self.inputs[1].value.reshape(-1, 1)\n",
    "        assert(y.shape == a.shape)\n",
    "\n",
    "        self.m = self.inputs[0].value.shape[0]\n",
    "        self.diff = y - a\n",
    "\n",
    "        self.value = np.mean(self.diff**2)\n",
    "\n",
    "\n",
    "    def backward(self):\n",
    "        #反向计算相应梯度\n",
    "        self.gradients[self.inputs[0]] = (2 / self.m) * self.diff\n",
    "        self.gradients[self.inputs[1]] = (-2 / self.m) * self.diff\n",
    "\n",
    "\n",
    "def forward_and_backward(outputnode, graph):\n",
    "    # execute all the forward method of sorted_nodes.\n",
    "\n",
    "    ## In practice, it's common to feed in mutiple data example in each forward pass rather than just 1. Because the examples can be processed in parallel. The number of examples is called batch size.\n",
    "    for n in graph:\n",
    "        n.forward()\n",
    "        ## each node execute forward, get self.value based on the topological sort result.\n",
    "\n",
    "    for n in  graph[::-1]:\n",
    "        n.backward()\n",
    "\n",
    "    #return outputnode.value\n",
    "\n",
    "###   v -->  a -->  C\n",
    "##    b --> C\n",
    "##    b --> v -- a --> C\n",
    "##    v --> v ---> a -- > C\n",
    "\n",
    "def topological_sort(feed_dict):\n",
    "    \"\"\"\n",
    "    Sort generic nodes in topological order using Kahn's Algorithm.\n",
    "    `feed_dict`: A dictionary where the key is a `Input` node and the value is the respective value feed to that node.\n",
    "    Returns a list of sorted nodes.\n",
    "    \"\"\"\n",
    "\n",
    "    input_nodes = [n for n in feed_dict.keys()]\n",
    "\n",
    "    G = {}\n",
    "    nodes = [n for n in input_nodes]\n",
    "    while len(nodes) > 0:\n",
    "        n = nodes.pop(0)\n",
    "        if n not in G:\n",
    "            G[n] = {'in': set(), 'out': set()}\n",
    "        for m in n.outputs:\n",
    "            if m not in G:\n",
    "                G[m] = {'in': set(), 'out': set()}\n",
    "            G[n]['out'].add(m)\n",
    "            G[m]['in'].add(n)\n",
    "            nodes.append(m)\n",
    "\n",
    "    L = []\n",
    "    S = set(input_nodes)\n",
    "    while len(S) > 0:\n",
    "        n = S.pop()\n",
    "\n",
    "        if isinstance(n, Input):\n",
    "            n.value = feed_dict[n]\n",
    "            ## if n is Input Node, set n'value as \n",
    "            ## feed_dict[n]\n",
    "            ## else, n's value is caculate as its\n",
    "            ## inbounds\n",
    "\n",
    "        L.append(n)\n",
    "        for m in n.outputs:\n",
    "            G[n]['out'].remove(m)\n",
    "            G[m]['in'].remove(n)\n",
    "            # if no other incoming edges add to S\n",
    "            if len(G[m]['in']) == 0:\n",
    "                S.add(m)\n",
    "    return L\n",
    "\n",
    "\n",
    "def sgd_update(trainables, learning_rate=1e-2):\n",
    "    # there are so many other update / optimization methods\n",
    "    # such as Adam, Mom, \n",
    "    for t in trainables:\n",
    "        t.value += -1 * learning_rate * t.gradients[t]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number of example = 506\n",
      "Epoch: 1, Loss: 210.046\n",
      "Epoch: 101, Loss: 5.536\n",
      "Epoch: 201, Loss: 5.192\n",
      "Epoch: 301, Loss: 5.451\n",
      "Epoch: 401, Loss: 3.777\n",
      "Epoch: 501, Loss: 3.848\n",
      "Epoch: 601, Loss: 3.300\n",
      "Epoch: 701, Loss: 3.063\n",
      "Epoch: 801, Loss: 3.140\n",
      "Epoch: 901, Loss: 2.934\n",
      "Epoch: 1001, Loss: 3.276\n",
      "Epoch: 1101, Loss: 3.103\n",
      "Epoch: 1201, Loss: 3.147\n",
      "Epoch: 1301, Loss: 2.545\n",
      "Epoch: 1401, Loss: 2.948\n",
      "Epoch: 1501, Loss: 2.771\n",
      "Epoch: 1601, Loss: 2.499\n",
      "Epoch: 1701, Loss: 2.932\n",
      "Epoch: 1801, Loss: 2.817\n",
      "Epoch: 1901, Loss: 2.751\n",
      "Epoch: 2001, Loss: 3.055\n",
      "Epoch: 2101, Loss: 2.820\n",
      "Epoch: 2201, Loss: 3.039\n",
      "Epoch: 2301, Loss: 2.417\n",
      "Epoch: 2401, Loss: 2.497\n",
      "Epoch: 2501, Loss: 2.884\n",
      "Epoch: 2601, Loss: 2.843\n",
      "Epoch: 2701, Loss: 2.780\n",
      "Epoch: 2801, Loss: 2.865\n",
      "Epoch: 2901, Loss: 2.915\n",
      "Epoch: 3001, Loss: 2.750\n",
      "Epoch: 3101, Loss: 2.701\n",
      "Epoch: 3201, Loss: 3.096\n",
      "Epoch: 3301, Loss: 2.445\n",
      "Epoch: 3401, Loss: 2.949\n",
      "Epoch: 3501, Loss: 2.709\n",
      "Epoch: 3601, Loss: 2.510\n",
      "Epoch: 3701, Loss: 2.746\n",
      "Epoch: 3801, Loss: 2.363\n",
      "Epoch: 3901, Loss: 2.628\n",
      "Epoch: 4001, Loss: 2.825\n",
      "Epoch: 4101, Loss: 2.712\n",
      "Epoch: 4201, Loss: 2.659\n",
      "Epoch: 4301, Loss: 2.729\n",
      "Epoch: 4401, Loss: 2.851\n",
      "Epoch: 4501, Loss: 2.568\n",
      "Epoch: 4601, Loss: 2.748\n",
      "Epoch: 4701, Loss: 2.467\n",
      "Epoch: 4801, Loss: 2.285\n",
      "Epoch: 4901, Loss: 2.689\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from sklearn.datasets import load_boston\n",
    "from sklearn.utils import shuffle, resample\n",
    "\n",
    "\n",
    "losses = []\n",
    "\n",
    "# Load data\n",
    "data = load_boston()\n",
    "X_ = data['data']\n",
    "y_ = data['target']\n",
    "\n",
    "\n",
    "# Normalize data\n",
    "X_ = (X_ - np.mean(X_, axis = 0)) / np.std(X_, axis = 0)    # （X - 均值）/ 标准差\n",
    "#print(np.mean(X_, axis = 0).shape)\n",
    "n_features = X_.shape[1]  # 特征的数量\n",
    "#print(n_features)      # 13个\n",
    "n_hidden = 10\n",
    "W1_ = np.random.randn(n_features, n_hidden)\n",
    "b1_ = np.zeros(n_hidden)\n",
    "W2_ = np.random.randn(n_hidden, 1)\n",
    "b2_ = np.zeros(1)\n",
    "\n",
    "# Neural network\n",
    "X, y = Input(), Input()\n",
    "W1, b1 = Input(), Input()\n",
    "W2, b2 = Input(), Input()\n",
    "\n",
    "l1 = Linear(X, W1, b1)\n",
    "s1 = Sigmoid(l1)\n",
    "l2 = Linear(s1, W2, b2)\n",
    "cost = MSE(y, l2)\n",
    "\n",
    "feed_dict = {\n",
    "    X:X_,\n",
    "    y:y_,\n",
    "    W1:W1_,\n",
    "    b1:b1_,\n",
    "    W2:W2_,\n",
    "    b2:b2_\n",
    "}\n",
    "\n",
    "epochs = 5000\n",
    "m = X_.shape[0]  # 总共有506个样本\n",
    "#print(m)        # 506\n",
    "batch_size = 16\n",
    "\n",
    "steps_per_epoch = m // batch_size    # 一次16个样本，更新31次\n",
    "# print(steps_per_epoch)   \n",
    "graph = topological_sort(feed_dict)\n",
    "trainables = [W1, b1, W2, b2]\n",
    "\n",
    "print(\"Total number of example = {}\".format(m))\n",
    "\n",
    "# Step 4\n",
    "for i in range(epochs):\n",
    "    loss = 0\n",
    "    for j in range(steps_per_epoch):\n",
    "        \n",
    "        # Step 1\n",
    "        # Randomly sample a batch of examples\n",
    "        X_batch, y_batch = resample(X_, y_, n_samples=batch_size)\n",
    "        \n",
    "        # Reset value of X and y Inputs\n",
    "        X.value = X_batch\n",
    "        y.value = y_batch\n",
    "        \n",
    "        # Step 2\n",
    "        _ = None\n",
    "        forward_and_backward(_, graph) # set output node not important.\n",
    "\n",
    "        # Step 3\n",
    "        rate = 1e-2\n",
    "    \n",
    "        sgd_update(trainables, rate)\n",
    "\n",
    "        loss += graph[-1].value\n",
    "    \n",
    "    if i % 100 == 0: \n",
    "        print(\"Epoch: {}, Loss: {:.3f}\".format(i+1, loss/steps_per_epoch))\n",
    "        losses.append(loss)\n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def forward(outputNode, graph):\n",
    "    for n in graph:\n",
    "        n.forward()\n",
    "    return outputNode.value"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[49.54743024],\n",
       "       [20.89227375],\n",
       "       [14.81019977],\n",
       "       [20.97910385],\n",
       "       [10.91702821],\n",
       "       [33.23583796],\n",
       "       [23.55708228],\n",
       "       [27.55472414],\n",
       "       [15.32053549],\n",
       "       [28.81160282],\n",
       "       [46.94278195],\n",
       "       [27.87985814],\n",
       "       [21.00695813],\n",
       "       [18.58499345],\n",
       "       [25.30435924],\n",
       "       [28.81160282]])"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "forward(l2, graph)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "78.3765164764184\n"
     ]
    }
   ],
   "source": [
    "print(losses)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x2095c4d8c18>]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX0AAAD4CAYAAAAAczaOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8li6FKAAAa+ElEQVR4nO3dbYxc133f8e9v7jwtnyxRWioqSZtyStSWhEquWEGug9ax0ohJjFBvBDBAKqIVQEBQCwdIEUh5E6QFAQMFgkRAJUCwXVGIE4FI7IpwrTQEYyMtIlhe2XJkPVWEZUssGXIl1eaK4j7MzL8v7pndy+WSHFLcXfqe3wcY3Dtn7929Z3b2t/85585cRQRmZpaHxmofgJmZrRyHvplZRhz6ZmYZceibmWXEoW9mlpHmah/AxVx//fWxbdu21T4MM7OfKy+88MI7ETG+uP2qD/1t27YxMTGx2odhZvZzRdJPlmr38I6ZWUYc+mZmGXHom5llxKFvZpYRh76ZWUYc+mZmGXHom5llpLahv//vfszBHxxb7cMwM7uq1Db0v/qdn/DNvz++2odhZnZVqW3od1sFM73+ah+GmdlVpbah32k2mOkNVvswzMyuKjUO/YLpOVf6ZmZVNQ59V/pmZovVN/RbDn0zs8XqG/pNT+SamS1W29DvthrMzLnSNzOrqm3ol5W+Q9/MrKrGod/w2TtmZovUOvRnegMiYrUPxczsqlHf0G8VAMz2PcRjZjZU39Bvll3zuL6Z2YKRQl/SNZL+QtJrkl6V9GlJGyUdkvRGWl5b2f4RSUckvS7pnkr7HZJeSl97VJKWo1OwUOn7DB4zswWjVvp/AvxVRHwCuA14FXgYOBwR24HD6T6SbgZ2A7cAO4HHJBXp+zwO7AW2p9vOK9SPcyxU+p7MNTMbumjoS9oA/EvgywARMRsRPwV2AfvTZvuBe9P6LuDpiJiJiDeBI8Cdkm4ENkTEc1HOrj5V2eeKG4b+tCt9M7N5o1T6Hwcmgf8m6fuSviRpLXBDRBwHSMtNafvNwNuV/Y+mts1pfXH7OSTtlTQhaWJycvKSOjTUaabhHVf6ZmbzRgn9JvDPgMcj4lPAadJQznksNU4fF2g/tzHiiYjYERE7xsfHRzjEc3Vansg1M1tslNA/ChyNiO+k+39B+U/gRBqyIS1PVrbfWtl/C3AstW9Zon1ZdJueyDUzW+yioR8R/wC8LemfpKa7gVeAg8Ce1LYHeCatHwR2S+pIuolywvb5NAQ0JemudNbO/ZV9rriFSt/DO2ZmQ80Rt/sPwFcltYEfAf+W8h/GAUkPAG8B9wFExMuSDlD+Y+gBD0XEMHkfBJ4ExoBn021Z+Dx9M7NzjRT6EfEisGOJL919nu33AfuWaJ8Abr2UA7xcw4lcf/6OmdkCvyPXzCwj9Q19n71jZnaO2oZ+d/5jGDy8Y2Y2VNvQ9/COmdm5ahv67cKhb2a2WG1DX1J5IRUP75iZzatt6MPC1bPMzKxU79BvFX5HrplZRa1Dv9tq+LN3zMwqah36nWbh4R0zs4qah37DwztmZhW1D31fOcvMbEHNQ98TuWZmVfUO/ZZP2TQzq6p16Hebhc/eMTOrqHXol5W+h3fMzIbqHfp+R66Z2VlqHvqFr5xlZlZR89B3pW9mVlXv0PfZO2ZmZ6l16HebBf1B0Os7+M3MYMTQl/RjSS9JelHSRGrbKOmQpDfS8trK9o9IOiLpdUn3VNrvSN/niKRHJenKd2mBr5NrZna2S6n0fzkibo+IHen+w8DhiNgOHE73kXQzsBu4BdgJPCapSPs8DuwFtqfbzg/fhfPrNNN1ch36ZmbAhxve2QXsT+v7gXsr7U9HxExEvAkcAe6UdCOwISKei4gAnqrssyyG18n1GTxmZqVRQz+Av5b0gqS9qe2GiDgOkJabUvtm4O3KvkdT2+a0vrh92Xh4x8zsbM0Rt/tMRByTtAk4JOm1C2y71Dh9XKD93G9Q/mPZC/DRj350xEM818Lwjit9MzMYsdKPiGNpeRL4OnAncCIN2ZCWJ9PmR4Gtld23AMdS+5Yl2pf6eU9ExI6I2DE+Pj56bxbpDit9f/6OmRkwQuhLWitp/XAd+FXgh8BBYE/abA/wTFo/COyW1JF0E+WE7fNpCGhK0l3prJ37K/ssC0/kmpmdbZThnRuAr6ezK5vAn0XEX0n6LnBA0gPAW8B9ABHxsqQDwCtAD3goIobjKw8CTwJjwLPptmyGE7ke3jEzK1009CPiR8BtS7S/C9x9nn32AfuWaJ8Abr30w7w8w0rfV88yMyvV+h25C2fvuNI3M4O6h37TE7lmZlW1Dv1uyxO5ZmZVtQ59T+SamZ2t5qHvSt/MrKrWod/2Z++YmZ2l1qFfNESrkCt9M7Ok1qEP5YVUfPaOmVmp9qFfXjLRwztmZpBD6DcLD++YmSUZhL4vjm5mNlT70G83Gz57x8wsqX3od1oe3jEzG6p96HebDWZc6ZuZARmEvit9M7MF9Q99T+Samc3LJPQ9vGNmBlmEvt+Ra2Y2VP/Q9ztyzczm1T70/dk7ZmYLah/6ZaXv0DczgxxCv9lgtj9gMIjVPhQzs1U3cuhLKiR9X9I30v2Nkg5JeiMtr61s+4ikI5Jel3RPpf0OSS+lrz0qSVe2O+fy1bPMzBZcSqX/BeDVyv2HgcMRsR04nO4j6WZgN3ALsBN4TFKR9nkc2AtsT7edH+roR+Dr5JqZLRgp9CVtAX4D+FKleRewP63vB+6ttD8dETMR8SZwBLhT0o3Ahoh4LiICeKqyz7LptIah70rfzGzUSv+Pgd8Dqsl5Q0QcB0jLTal9M/B2ZbujqW1zWl/cfg5JeyVNSJqYnJwc8RCX1h0O7/gMHjOzi4e+pM8DJyPihRG/51Lj9HGB9nMbI56IiB0RsWN8fHzEH7u0hUrfwztmZs0RtvkM8JuSfh3oAhsk/SlwQtKNEXE8Dd2cTNsfBbZW9t8CHEvtW5ZoX1aeyDUzW3DRSj8iHomILRGxjXKC9m8i4reBg8CetNke4Jm0fhDYLakj6SbKCdvn0xDQlKS70lk791f2WTbDiVxfSMXMbLRK/3y+CByQ9ADwFnAfQES8LOkA8ArQAx6KiGHiPgg8CYwBz6bbslo4e8eVvpnZJYV+RHwb+HZafxe4+zzb7QP2LdE+Adx6qQf5YXRaw+EdV/pmZrV/R253OJHrs3fMzOof+p7INTNbkEHo+5RNM7OhbEJ/2sM7ZmYZhL4ncs3M5tU/9JueyDUzG6p96LeKBkVDnsg1MyOD0Iey2vfwjplZVqHvSt/MLJPQL/zZO2Zm5BL6vji6mRmQS+g3Gz57x8yMTEK/2yo8kWtmRiah74lcM7NSJqFfOPTNzMgm9Bs+e8fMjFxC32fvmJkBmYR+t+mJXDMzyCT0Oy2fsmlmBrmEvidyzcyAbELfH7hmZgYZhf703ICIWO1DMTNbVRcNfUldSc9L+oGklyX9YWrfKOmQpDfS8trKPo9IOiLpdUn3VNrvkPRS+tqjkrQ83Trb8OpZs30P8ZhZ3kap9GeAz0XEbcDtwE5JdwEPA4cjYjtwON1H0s3AbuAWYCfwmKQifa/Hgb3A9nTbeQX7cl4LF0d36JtZ3i4a+lF6P91tpVsAu4D9qX0/cG9a3wU8HREzEfEmcAS4U9KNwIaIeC7KcZanKvssq/nr5PoMHjPL3Ehj+pIKSS8CJ4FDEfEd4IaIOA6QlpvS5puBtyu7H01tm9P64valft5eSROSJiYnJy+lP0taqPQ9mWtmeRsp9COiHxG3A1soq/ZbL7D5UuP0cYH2pX7eExGxIyJ2jI+Pj3KIF+ThHTOz0iWdvRMRPwW+TTkWfyIN2ZCWJ9NmR4Gtld22AMdS+5Yl2pddp1kO7/jzd8wsd6OcvTMu6Zq0Pgb8CvAacBDYkzbbAzyT1g8CuyV1JN1EOWH7fBoCmpJ0Vzpr5/7KPsuq03Klb2YG0BxhmxuB/ekMnAZwICK+Iek54ICkB4C3gPsAIuJlSQeAV4Ae8FBEDEvsB4EngTHg2XRbdt2mJ3LNzGCE0I+Ivwc+tUT7u8Dd59lnH7BvifYJ4ELzActiodL38I6Z5S2bd+SCh3fMzDIJ/TS849A3s8xlEvplN332jpnlLo/Q99k7ZmZAJqHfnf8YBlf6Zpa3LELfE7lmZqUsQr9dOPTNzCCT0Jfkq2eZmZFJ6EO6ZKLfkWtmmcsn9FuFK30zy142od9tudI3M8sm9DvNwhO5Zpa9jELfE7lmZpmFvit9M8tbRqFf+LN3zCx7+YR+y5W+mVk2od9tFj57x8yyl03ol5W+h3fMLG/5hL4ncs3Mcgp9n6dvZpZR6Dd89o6ZZS+f0PfZO2ZmFw99SVslfUvSq5JelvSF1L5R0iFJb6TltZV9HpF0RNLrku6ptN8h6aX0tUclaXm6da5us6A/CHp9B7+Z5WuUSr8H/G5EfBK4C3hI0s3Aw8DhiNgOHE73SV/bDdwC7AQek1Sk7/U4sBfYnm47r2BfLsjXyTUzGyH0I+J4RHwvrU8BrwKbgV3A/rTZfuDetL4LeDoiZiLiTeAIcKekG4ENEfFcRATwVGWfZddppuvkOvTNLGOXNKYvaRvwKeA7wA0RcRzKfwzAprTZZuDtym5HU9vmtL64famfs1fShKSJycnJSznE81q4Tq4nc80sXyOHvqR1wF8CvxMRpy606RJtcYH2cxsjnoiIHRGxY3x8fNRDvKDh8M6035VrZhkbKfQltSgD/6sR8bXUfCIN2ZCWJ1P7UWBrZfctwLHUvmWJ9hXRnR/ecaVvZvka5ewdAV8GXo2IP6p86SCwJ63vAZ6ptO+W1JF0E+WE7fNpCGhK0l3pe95f2WfZzU/kutI3s4w1R9jmM8C/AV6S9GJq+33gi8ABSQ8AbwH3AUTEy5IOAK9QnvnzUEQMy+sHgSeBMeDZdFsRnsg1Mxsh9CPif7P0eDzA3efZZx+wb4n2CeDWSznAK8UTuWZmOb0jd1jpe3jHzDKWT+gPz95xpW9mGcsm9Luu9M3M8gl9fwyDmVlOoe+JXDOznELfp2yamWUT+u3m8GMYXOmbWb6yCf2iIVqFXOmbWdayCX0oz+Dx2TtmlrOsQr+8ZKKHd8wsX3mFfrPw8I6ZZS2z0PfF0c0sb1mFfrvZ8Nk7Zpa1rEK/0/LwjpnlLavQ7zYbzLjSN7OMZRX6rvTNLHd5hb4ncs0scxmGvod3zCxfmYW+35FrZnnLK/T9jlwzy1xWoe/P3jGz3F009CV9RdJJST+stG2UdEjSG2l5beVrj0g6Iul1SfdU2u+Q9FL62qOSdOW7c2Flpe/QN7N8jVLpPwnsXNT2MHA4IrYDh9N9JN0M7AZuSfs8JqlI+zwO7AW2p9vi77nsOs0Gs/0Bg0Gs9I82M7sqXDT0I+JvgfcWNe8C9qf1/cC9lfanI2ImIt4EjgB3SroR2BARz0VEAE9V9lkxw6tnzfZd7ZtZni53TP+GiDgOkJabUvtm4O3KdkdT2+a0vrh9SZL2SpqQNDE5OXmZh3iujq+eZWaZu9ITuUuN08cF2pcUEU9ExI6I2DE+Pn7FDq7TGl4c3ZW+meXpckP/RBqyIS1PpvajwNbKdluAY6l9yxLtK6o7vDi6z+Axs0xdbugfBPak9T3AM5X23ZI6km6inLB9Pg0BTUm6K521c39lnxWzUOl7eMfM8tS82AaS/hz4LHC9pKPAHwBfBA5IegB4C7gPICJelnQAeAXoAQ9FxDBhH6Q8E2gMeDbdVtRwItfDO2aWq4uGfkT81nm+dPd5tt8H7FuifQK49ZKO7gobTuS60jezXGX1jtyFs3dc6ZtZnvIK/dZweMeVvpnlKavQ7w4ncl3pm1mmsgp9T+SaWe4yC31P5JpZ3jINfVf6ZpanvEI/TeT6s3fMLFdZhX636YlcM8tbVqHfLBoUDXl4x8yylVXoQzmu74lcM8tVpqHvSt/M8pRh6Pvi6GaWr/xCv9Vg2sM7Zpap7EK/60rfzDKWXeh3Wp7INbN85Rf6nsg1s4xlGPqFQ9/MspVh6Ht4x8zylV/otxq+cpaZZeui18itm26r4M13TvOv/su3WNtusq7bZF2nvA3H+8/M9Zme63Nmts+ZuT69fnDL5g18+uPX8S/+8fVsvmZstbthZnZZsgv9PZ/eRrdV8P50j9MzPd6f6XHi1DQ/mukxPTdgrF3QbRWMtRqMtQuuWdMGgm+/PsnXvvd/AfjYdWv49Mev49O/eB3Xre0wiKAfwWAQ9AfBIIJuq+D6dR02rm2zcW2bbvqETzOz1ZRd6N+29Rpu23rNJe83GAT/5+QUf3fkXZ770bv8j5eO8/R33x55/3WdJteta3PNWItOq/zH0m2W/1i6zYJ2s8Egyn8Y/UHQH0B/MGAQ0G426DQbdJoFnVa53m42mOsFp2d7TKV/YKdnekzN9OgPgnZRbtNuNubXmw0xCAiCCBhEuZRg49o216/rML4+3dZ1uG5dm9negFNnekxNz3Fqeo5TZ3qcmp5jEMOfUZz1czqtBmtaBWvaTcbaDcbaTda0CopCnDozx8/Sbbg+Nd2jIdEsRLNRHmOzEEUj3SSk4X2QRK8ffDDb4/RM/6xlbxB0Ww26zfT4thp0WgXtopzHmekNmJ7rMzM3YLrXZ64fXLOmxab13fk+j6/vcN3aNo2Gzvrd99PvZXquz9R0+RhMTZeP/akzc0z3+gjREDQkSMvhfQmKhlJb2V7+rqE3GMyvD3/n5XMBIhUTAQhoNwtaheYf71bRoNVsnPVzhj8jInh/pjd/vKfS4z0102NDt8UNGzpsWt+dX27a0AHgvdOzvHd6lv/3QVqenmW2P0jP2YJuu3zudluVxzk9Dzrp1mo2mE2Pd3kbzC+7rQbruy3WdZus7zZZ126e9Xj3+uWr7eEr7em5wfzvb2ZuwGy//B3ODYJi/rkjmkV6/jREo1E+xqo83g1p/nHtD4KIYZFW3p8bDOj1g16//N79QTkMPNYqyudxu2CsVbA2jQr0+jF/XLP9AbO9AXP9Ae2ikZ7/BWvSbaxdPg8lcT4RwenZ/vzv6dT0HP9828ZLC6oRrHjoS9oJ/AlQAF+KiC+u9DFcjkZDfOIXNvCJX9jAv/ulm+gPgtf+4RSnZ/oUjYU/tOEf9pm5Hu++P8u76Q/onfdneO/0LD87M8f0XJ+fnZnj5HAYaa7PbG9Qfo/hk3b+e8Hc8MlVCauhbqsxPzy1Ni27rfIP7oMPesz2g9len9n+gH4/UCUYhsv+IHjv9Czvz/RW8RH+cLqtBoXKT1DtDeKi2xfpcV7qTK6GoNlozAd9nbSb5fNlanrurOfRapJgXbuJBGfm+lfNcV1pEvMFWKdSjPUj5ouHxU+31/7zzis+SrCioS+pAP4r8K+Bo8B3JR2MiFdW8jiuhKIhbvlHH1mVn90fBLO9Aa2irG6ulDOzfd55f4aTUzO88/4M774/S6fZYMNYiw3dJuu7LTaMlcuiIWZ7g4Vbf1hJlxXdB6lKOzPb44PZPv1BsKHbKr/XWJOPjLX4yFiL9d0WBMwNBmW11R8u46xXPpGqsX56hbGmXVZcZSXVpKhUinP9wVnV5Vx/UL66ajbml8PH7YPZHpNTM0xOlf0ervcGQdGAIv0jHi67rYL13WbZl/SYrO+WVV2kV1GDKF8dDH9XQaWyjGAwKCv54Suc4T/4YYVaqFqlLiwHUfZtNlWWc5XqsnzlxvxjFik81nXKanp4nMMAGQyCn56Z48SpaU5OzXDi1DSTUzPlq741ba5d2+baNW02rm1x7Zo2nVZRqdoXHtthwTLTG8wXJsOqt119NZBe1Xaaxfyrpan5V0tznJouC46xVE2vmR9mXXg10R6+2m2WryibjQb9QdAbVuiDskrvDRZeyQ4fi+HzaPhYL37lVaRXmK1Go1ymV56R/i7OzJXP49Mz5frM3IBW9dV0s0GnWHiF88Fs+erzzOzC38J05bGa7Q/mH6tCpL+x8m9jQ7c1/7dWfV5fKStd6d8JHImIHwFIehrYBfzchf5qKhpirH3l5wjG2gVbN65h68Y1o+3QueKHcEW00rDH+u7Ft13TbvKx65p87Lq1y39gV5FGQ/PzTZ+8cbR91nWyGw2upZU+ZXMzUB0IP5raziJpr6QJSROTk5MrdnBmZnW30qG/1GuVcwbwIuKJiNgRETvGx8dX4LDMzPKw0qF/FNhaub8FOLbCx2Bmlq2VDv3vAtsl3SSpDewGDq7wMZiZZWtFZ2Yioifp3wP/k/KUza9ExMsreQxmZjlb8en4iPgm8M2V/rlmZpbhB66ZmeXMoW9mlhFFXN1veZY0CfzkMne/HnjnCh7Ozwv3Oy/ud15G7ffHIuKcc96v+tD/MCRNRMSO1T6OleZ+58X9zsuH7beHd8zMMuLQNzPLSN1D/4nVPoBV4n7nxf3Oy4fqd63H9M3M7Gx1r/TNzKzCoW9mlpFahr6knZJel3RE0sOrfTzLSdJXJJ2U9MNK20ZJhyS9kZbXruYxLgdJWyV9S9Krkl6W9IXUXuu+S+pKel7SD1K//zC117rfUF55T9L3JX0j3a99nwEk/VjSS5JelDSR2i6777UL/colGX8NuBn4LUk3r+5RLasngZ2L2h4GDkfEduBwul83PeB3I+KTwF3AQ+n3XPe+zwCfi4jbgNuBnZLuov79BvgC8Grlfg59HvrliLi9cn7+Zfe9dqFP5ZKMETELDC/JWEsR8bfAe4uadwH70/p+4N4VPagVEBHHI+J7aX2KMgw2U/O+R+n9dLeVbkHN+y1pC/AbwJcqzbXu80Vcdt/rGPojXZKx5m6IiONQhiOwaZWPZ1lJ2gZ8CvgOGfQ9DXO8CJwEDkVEDv3+Y+D3gEGlre59HgrgryW9IGlvarvsvtfxSscjXZLR6kHSOuAvgd+JiFPSUr/+eomIPnC7pGuAr0u6dbWPaTlJ+jxwMiJekPTZ1T6eVfCZiDgmaRNwSNJrH+ab1bHS9yUZ4YSkGwHS8uQqH8+ykNSiDPyvRsTXUnMWfQeIiJ8C36ac06lzvz8D/KakH1MO135O0p9S7z7Pi4hjaXkS+DrlEPZl972Ooe9LMpb93ZPW9wDPrOKxLAuVJf2XgVcj4o8qX6p13yWNpwofSWPArwCvUeN+R8QjEbElIrZR/j3/TUT8NjXu85CktZLWD9eBXwV+yIfoey3fkSvp1ynHAIeXZNy3yoe0bCT9OfBZyo9bPQH8AfDfgQPAR4G3gPsiYvFk7881Sb8E/C/gJRbGeX+fcly/tn2X9E8pJ+4KyqLtQET8J0nXUeN+D6Xhnf8YEZ/Poc+SPk5Z3UM5HP9nEbHvw/S9lqFvZmZLq+PwjpmZnYdD38wsIw59M7OMOPTNzDLi0Dczy4hD38wsIw59M7OM/H+xbwvSnp6V0gAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.plot(range(len(losses)), losses)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[10.17538735],\n",
       "       [10.56550596],\n",
       "       [ 7.58417273],\n",
       "       [ 7.23629406],\n",
       "       [-7.74907778],\n",
       "       [ 8.42191248],\n",
       "       [17.60452894],\n",
       "       [ 6.72216926],\n",
       "       [ 8.04815893],\n",
       "       [ 4.77634839]])"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "W2.value"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3319, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-12-88d96843a926>\", line 1, in <module>\n",
      "    import keras\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
      "    from . import utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
      "    from . import conv_utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
      "    from .. import backend as K\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
      "    from .load_backend import epsilon\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
      "    from .tensorflow_backend import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
      "    from tensorflow.python.tools import module_util as _module_util\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 1495, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 1453, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
      "    from . _api.v2 import audio\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 9, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3319, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-12-88d96843a926>\", line 1, in <module>\n",
      "    import keras\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
      "    from . import utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
      "    from . import conv_utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
      "    from .. import backend as K\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
      "    from .load_backend import epsilon\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
      "    from .tensorflow_backend import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
      "    from tensorflow.python.tools import module_util as _module_util\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3319, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-12-88d96843a926>\", line 1, in <module>\n",
      "    import keras\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
      "    from . import utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
      "    from . import conv_utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
      "    from .. import backend as K\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
      "    from .load_backend import epsilon\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
      "    from .tensorflow_backend import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
      "    from tensorflow.python.tools import module_util as _module_util\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3242, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3336, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2037, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1418, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1318, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1186, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: can only concatenate str (not \"list\") to str\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1151, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 1495, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 1453, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 42, in <module>\n",
      "    from . _api.v2 import audio\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\_api\\v2\\audio\\__init__.py\", line 10, in <module>\n",
      "    from tensorflow.python.ops.gen_audio_ops import decode_wav\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\ops\\gen_audio_ops.py\", line 9, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3319, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-12-88d96843a926>\", line 1, in <module>\n",
      "    import keras\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\__init__.py\", line 3, in <module>\n",
      "    from . import utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\__init__.py\", line 6, in <module>\n",
      "    from . import conv_utils\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\utils\\conv_utils.py\", line 9, in <module>\n",
      "    from .. import backend as K\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\__init__.py\", line 1, in <module>\n",
      "    from .load_backend import epsilon\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\load_backend.py\", line 90, in <module>\n",
      "    from .tensorflow_backend import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\keras\\backend\\tensorflow_backend.py\", line 5, in <module>\n",
      "    import tensorflow as tf\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 101, in <module>\n",
      "    from tensorflow_core import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\__init__.py\", line 40, in <module>\n",
      "    from tensorflow.python.tools import module_util as _module_util\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\__init__.py\", line 49, in <module>\n",
      "    from tensorflow.python import pywrap_tensorflow\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 74, in <module>\n",
      "    raise ImportError(msg)\n",
      "ImportError: Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ImportError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3242, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3336, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2037, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1418, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1318, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1186, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: can only concatenate str (not \"list\") to str\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2034, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\", line 58, in <module>\n",
      "    from tensorflow.python.pywrap_tensorflow_internal import *\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 28, in <module>\n",
      "    _pywrap_tensorflow_internal = swig_import_helper()\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n",
      "    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 243, in load_module\n",
      "    return load_dynamic(name, filename, file)\n",
      "  File \"f:\\app\\python3.7\\install\\lib\\imp.py\", line 343, in load_dynamic\n",
      "    return _load(spec)\n",
      "ImportError: DLL load failed: 找不到指定的模块。\n",
      "\n",
      "\n",
      "Failed to load the native TensorFlow runtime.\n",
      "\n",
      "See https://www.tensorflow.org/install/errors\n",
      "\n",
      "for some common reasons and solutions.  Include the entire stack trace\n",
      "above this error message when asking for help.\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "can only concatenate str (not \"list\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     57\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 58\u001b[1;33m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[1;33m*\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     59\u001b[0m   \u001b[1;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0m__version__\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     27\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0m_mod\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 28\u001b[1;33m     \u001b[0m_pywrap_tensorflow_internal\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     29\u001b[0m     \u001b[1;32mdel\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\tensorflow_core\\python\\pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mswig_import_helper\u001b[1;34m()\u001b[0m\n\u001b[0;32m     23\u001b[0m             \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 24\u001b[1;33m                 \u001b[0m_mod\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mimp\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mload_module\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'_pywrap_tensorflow_internal'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfp\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpathname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     25\u001b[0m             \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\imp.py\u001b[0m in \u001b[0;36mload_module\u001b[1;34m(name, file, filename, details)\u001b[0m\n\u001b[0;32m    242\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 243\u001b[1;33m             \u001b[1;32mreturn\u001b[0m \u001b[0mload_dynamic\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mname\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfilename\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    244\u001b[0m     \u001b[1;32melif\u001b[0m \u001b[0mtype_\u001b[0m \u001b[1;33m==\u001b[0m \u001b[0mPKG_DIRECTORY\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\imp.py\u001b[0m in \u001b[0;36mload_dynamic\u001b[1;34m(name, path, file)\u001b[0m\n\u001b[0;32m    342\u001b[0m             name=name, loader=loader, origin=path)\n\u001b[1;32m--> 343\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0m_load\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    344\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mImportError\u001b[0m: DLL load failed: 找不到指定的模块。",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2033\u001b[0m                         \u001b[1;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2034\u001b[1;33m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2035\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'ImportError' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[1;34m(self, code_obj, result, async_)\u001b[0m\n\u001b[0;32m   3334\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3335\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msys\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3336\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3337\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3338\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2035\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2036\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[1;32m-> 2037\u001b[1;33m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[0;32m   2038\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2039\u001b[0m                     \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1416\u001b[0m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1417\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[1;32m-> 1418\u001b[1;33m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[0;32m   1419\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1420\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1316\u001b[0m             \u001b[1;31m# Verbose modes need a full traceback\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1317\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[1;32m-> 1318\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1319\u001b[0m             )\n\u001b[0;32m   1320\u001b[0m         \u001b[1;32melif\u001b[0m \u001b[0mmode\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m'Minimal'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\app\\python3.7\\install\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1184\u001b[0m         \u001b[0mexception\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1185\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1186\u001b[1;33m             \u001b[0mformatted_exceptions\u001b[0m \u001b[1;33m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_chained_exception_message\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__cause__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1187\u001b[0m             \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1188\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: can only concatenate str (not \"list\") to str"
     ]
    }
   ],
   "source": [
    "import keras"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.layers import Dense\n",
    "from keras.models import Sequential\n",
    "\n",
    "model = Sequential\n",
    "\n",
    "model.add(Dense(units=64, activation='sigmoid', input_dim=13))\n",
    "model.add(Dense(units=30, activation='sigmoid', input_dim=64))\n",
    "\n",
    "model.add(Dense(units=1))\n",
    "\n",
    "model.compile(loss='mse',optimizer='sgd', metrics=['mse'])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
